// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace printSmart.Models
{
    public partial class Categorium
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
    }
}