// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace printSmart.Models
{
    public partial class MarcaSuministro
    {
        public MarcaSuministro()
        {
            Suministros = new HashSet<Suministro>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "La marca es obligatorio")]
        public string Marca { get; set; }

        public virtual ICollection<Suministro> Suministros { get; set; }
    }
}