// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace printSmart.Models
{
    public partial class MarcaMaquina
    {
        public MarcaMaquina()
        {
            Maquinas = new HashSet<Maquina>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string Marca { get; set; }

        public virtual ICollection<Maquina> Maquinas { get; set; }
    }
}