// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace printSmart.Models
{
    public partial class Paymentcc
    {
        public int Id { get; set; }

        [Display(Name = "Fecha de pago")]
        public DateTime Date { get; set; }

        [Display(Name = "Cantidad")]
        [Required(ErrorMessage = "Se requiere una cantidad valida para registrar")]
        public decimal Amount { get; set; }

        [Display(Name = "Descripcion")]
        public string Description { get; set; }

        [Display(Name = "Cliente")]
        public int IdCostumer { get; set; }

        [Display(Name = "Cliente")]
        public virtual Costumer IdCostumerNavigation { get; set; }
    }
}