// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace printSmart.Models
{
    public partial class Pc
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string Nombre { get; set; }

        [Display(Name = "Sistema Operativo")]
        public int SistemaOpId { get; set; }

        [Display(Name = "Marca")]
        public int MarcaId { get; set; }

        [Display(Name = "Procesador")]
        public int ProcesadorId { get; set; }


        [Required(ErrorMessage = "La RAM es obligatoria")]
        public string Ram { get; set; }

        [Required(ErrorMessage = "El disco duro es obligatoria")]
        [Display(Name = "Disco")]
        public string DiscoDuro { get; set; }

        [Required(ErrorMessage = "El tamaño de pantall es obligatoria")]
        public string Pantalla { get; set; }

        [Required(ErrorMessage = "El precio de venta obligatoria")]
        [Display(Name = "P.Venta")]
        public decimal PrecioVenta { get; set; }

        [Required(ErrorMessage = "El precio de compra obligatoria")]
        [Display(Name = "P.Compra")]
        public decimal PrecioCompra { get; set; }

        public virtual MarcaPc Marca { get; set; }
        public virtual Procesador Procesador { get; set; }

        [Display(Name = "Sis.Op")]
        public virtual SistemaOperativo SistemaOp { get; set; }
    }
}