// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace printSmart.Models
{
    public class Repuestod
    {
        public string Nombre;
        public float? Precio;
    }
    public partial class Repuesto
    {
        public Repuesto()
        {
            ServicioRepuesto = new HashSet<ServicioRepuesto>();
        }
        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El código es obligatorio")]
        public string Codigo { get; set; }

        [Required(ErrorMessage = "El modelo es obligatorio")]
        public string Modelo { get; set; }

        [Required(ErrorMessage = "La existencia es obligatoria")]
        public int Existencia { get; set; }

        [Required(ErrorMessage = "El precio de venta es obligatorio")]
        public decimal PrecioVenta { get; set; }

        [Required(ErrorMessage = "El precio de compra es obligatorio")]
        public decimal PrecioCompra { get; set; }

        public virtual ICollection<ServicioRepuesto> ServicioRepuesto { get; set; }
    }
}