// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace printSmart.Models
{
    public partial class SistemaOperativo
    {
        public SistemaOperativo()
        {
            Pcs = new HashSet<Pc>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio")]
        [Display(Name = "Sistema Operativo")]
        public string Nombre { get; set; }

        public virtual ICollection<Pc> Pcs { get; set; }
    }
}