// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace printSmart.Models
{
    public class Suministrod
    {
        public string Nombre;
        public float? Precio; 
            
    }
    public partial class Suministro
    {
        public Suministro()
        {
            ServicioSuministro = new HashSet<ServicioSuministro>();
        }
        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string Nombre { get; set; }

        [Display(Name = "Marca")]
        public int IdMarca { get; set; }

        [Display(Name = "Tipo")]
        public int IdTipo { get; set; }

        [Required(ErrorMessage = "El modelo es obligatorio")]
        public string Modelo { get; set; }

        [Required(ErrorMessage = "La existencia es obligatorio")]
        public int Existencia { get; set; }

        [Required(ErrorMessage = "El precio de compra es obligatorio")]
        public decimal PrecioCompra { get; set; }

        [Required(ErrorMessage = "El precion de venta es obligatorio")]
        public float PrecioVenta { get; set; }


        [Display(Name = "Marca")]
        public virtual MarcaSuministro IdMarcaNavigation { get; set; }

        [Display(Name = "Tipo")]
        public virtual TipoSuministro IdTipoNavigation { get; set; }

        public virtual ICollection<ServicioSuministro> ServicioSuministro { get; set; }
    }
}