// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace printSmart.Models
{
    public partial class TipoSuministro
    {
        public TipoSuministro()
        {
            Suministros = new HashSet<Suministro>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio")]
        [Display(Name = "Tipo")]
        public string NombreTipo { get; set; }

        public virtual ICollection<Suministro> Suministros { get; set; }
    }
}